name: shard
version: git
summary: Shard is a light mythril client
description: |
    Shard is an cli that provides access to the mythril platform

grade: devel
confinement: devmode


parts:
  shard:
    source: https://github.com/JoranHonig/shard.git
    source-type: git
    plugin: go
    go-importpath: github.com/JoranHonig/shard

apps:
  shard:
    command: shard
